export const ACTIONS = {
  CONTEXT_MENU: {
    OPEN_CONTEXT_MENU: 'OPEN_CONTEXT_MENU',
    CLOSE_CONTEXT_MENU: 'CLOSE_CONTEXT_MENU',
    TOGGLE_CONTEXT_MENU: 'TOGGLE_CONTEXT_MENU',
  },
  START_MENU: {
    TOGGLE_START_MENU: 'TOGGLE_START_MENU',
  },
  APP_WINDOWS: {
    OPEN_APP_WINDOW: 'OPEN_APP_WINDOW'
  }
}
