export const ACTIONS = {
  CONTEXT_MENU: {
    OPEN_CONTEXT_MENU: 'OPEN_CONTEXT_MENU',
    CLOSE_CONTEXT_MENU: 'CLOSE_CONTEXT_MENU',
    TOGGLE_CONTEXT_MENU: 'TOGGLE_CONTEXT_MENU',
  },
  START_MENU: {
    TOGGLE_START_MENU: 'TOGGLE_START_MENU',
  },
  APP_WINDOWS: {
    OPEN_APP_WINDOW: 'OPEN_APP_WINDOW',
    TOGGLE_APP_WINDOW_MAXIMIZED_STATUS: 'TOGGLE_APP_WINDOW_MAXIMIZED_STATUS',
    UPDATE_APP_WINDOW_POSITION: 'UPDATE_APP_WINDOW_POSITION',
    CLOSE_APP_WINDOW: 'CLOSE_APP_WINDOW',
  },
}

export const IDENTIFICATORS = {
  APP_WINDOW_DRAGGABLE: 'APP_WINDOW_DRAGGABLE',
}